### ISSUE TITLE
hadolint: binary not found in $PATH

### ISSUE THREAD

**Issue by jbnjohnathan** [mikybars/hadolint-wrapper#2]
Installed hadolintw==1.2.1 using pip

Showing help works
```
hadolintw --help
Usage: hadolintw [OPTIONS] DOCKERFILE [HADOLINT_ARGS]...

  Pretty output for hadolint

Options:
  -d, --use-docker             use the dockerized version of hadolint
  --color [never|auto|always]
  --help                       Show this message and exit.
```

Trying to lint a Dockerfile does not
```
hadolintw Dockerfile
hadolint: binary not found in $PATH
```

Which binary is this refering to?

**Comment by mikybars** [comment]
To run `hadolintw` you first need the `hadolint` (without w) binary in your `PATH`, as it's just a wrapper for it. You can find instructions on how to install it here:
https://github.com/hadolint/hadolint
